Repository Readme-Workflows/recent-activity, pull requests merged in 2021-08, with the labels that each got.

#89 Move to issue forms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: No changelog, Status: Ready

#90 Add amount keyword
  .eslintrc.json
  dist/index.js
  src/config.js
  src/events/PullRequestReviewEvent.js
  src/functions/amountReplacer.js
  src/functions/commitFile.js
  src/functions/execute.js
  src/functions/filterContent.js
  src/functions/makeCustomUrl.js
  src/functions/toUrlFormat.js
Labels: Priority: low, Status: Ready, minor

#91 Prepare Changelog and wiki for v2.3.1 release
  CHANGELOG.md
  docs/Configuration.md
Labels: Status: Ready, Updates: documentation

#97 Implement replacer for CHANGELOG file
  .github/replacer.json
  .github/workflows/update_changelog.yml
Labels: Status: Ready, No changelog

#103 Use Graphs for Stargazers and Contributions
  README.md
Labels: Updates: documentation, Status: Ready, No changelog
