Repository Readme-Workflows/recent-activity, pull requests merged in 2021-05, with the labels that each got.

#11 Issue#5
  ChangeLog.md
  README.md
  action.yml
  dist/index.js
  index.js
Labels: enhancement, minor

#13 Issue 4 - Option to disable specific activity types from being shown in the activity list
  ChangeLog.md
  README.md
  action.yml
  dist/index.js
  index.js
Labels: enhancement, minor

#20 Improve release-drafter.yml
  .github/dependabot.yml
  .github/release-drafter.yml
Labels: github actions

#17 Easier way to disable events
  .github/dependabot.yml
  .github/release-drafter.yml
  CHANGELOG.md
  ChangeLog.md
  README.md
  action.yml
  dist/index.js
  index.js
Labels: enhancement

#22 Update project files
  .github/dependabot.yml
  .github/release-drafter.yml
  CHANGELOG.md
Labels: documentation, github actions

#28 Run build workflow
  .github/workflows/run-build.yml
Labels: github actions

#29 Prepare Changelog for 1.2.2
  CHANGELOG.md
Labels: documentation

#32 Update run-build.yml
  .github/workflows/run-build.yml
  dist/index.js
  index.js
  node_modules/@vercel/ncc/dist/ncc/cli.js.cache
  node_modules/@vercel/ncc/dist/ncc/index.js.cache
  node_modules/@vercel/ncc/dist/ncc/loaders/relocate-loader.js.cache
  node_modules/@vercel/ncc/dist/ncc/loaders/shebang-loader.js.cache
Labels: github actions

#33 Single file for formatting and running build
  .github/workflows/node.js.yml
  .github/workflows/run-build.yml
Labels: github actions

#35 Create PR Commenter
  .github/label-commenter-config.yml
  .github/workflows/pr_comment.yml
Labels: Status: Ready, github actions

#34 Update README.md
  README.md
Labels: documentation

#36 Add badge for latest release
  README.md
Labels: Status: Ready, documentation

#38 Improve release-drafter
  .github/release-drafter.yml
Labels: Status: Ready

#41 Prepare Changelog for 1.3.0
  CHANGELOG.md
Labels: Status: Ready, Updates: documentation

#42 Easily get the URL of the issue/comment/pull_request
  .github/workflows/run-build.yml
  dist/index.js
  index.js
  package-lock.json
Labels: Status: Ready, Type: enhancement, minor

#43 Prepare Changelog for v1.4.0
  CHANGELOG.md
Labels: Status: Ready

#44 Improve Pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: No changelog, Status: Ready

#46 Add test-workflow and change preview to live preview
  .github/workflows/run-build.yml
  .github/workflows/test-workflow.yml
  README.md
  package.json
Labels: Status: Ready

#47 Improve CONTRIBUTING file
  .github/CONTRIBUTING.md
Labels: Status: Ready

#48 Fix copyright and Update package.json
  LICENSE
  config.js
  dist/index.js
  functions/appendDate.js
  functions/commitFile.js
  functions/execute.js
  functions/filterContent.js
  functions/makeCustomUrl.js
  functions/toUrlFormat.js
  index.js
  package.json
  serializers.js
Labels: Status: In progress

#51 Prepare Changelog
  CHANGELOG.md
Labels: No changelog, Status: Ready

#50 Add Create Repo Event, PR Review Event and PR Review Comment Event and Add separate module for each event
  CHANGELOG.md
  README.md
  action.yml
  config.js
  dist/index.js
  events/CommitCommentEvent.js
  events/CreateEvent.js
  events/ForkEvent.js
  events/GollumEvent.js
  events/IssueCommentEvent.js
  events/IssuesEvent.js
  events/MemberEvent.js
  events/PullRequestEvent.js
  events/PullRequestReviewCommentEvent.js
  events/PullRequestReviewEvent.js
  events/ReleaseEvent.js
  events/WatchEvent.js
  functions/filterContent.js
  functions/makeCustomUrl.js
  functions/toUrlFormat.js
  index.js
  serializers.js
Labels: Priority: medium, Status: Ready, Type: enhancement, minor

#55 Make a proper archive of old changelog
  .github/changelogs/CHANGELOG_v1.md
  CHANGELOG.md
Labels: Status: Ready

#54 Locale supported as timezone
  .github/changelogs/CHANGELOG_v1.md
  CHANGELOG.md
  README.md
  action.yml
  config.js
  dist/index.js
  functions/appendDate.js
Labels: Priority: medium, Status: Ready, Type: breaking, Updates: documentation, major

#56 Add #53 to changelog
  CHANGELOG.md
Labels: No changelog, Status: Ready, Updates: documentation

#53 Use config file
  .github/workflows/run-build.yml
  .github/workflows/test-workflow.yml
  .prettierignore
  CHANGELOG.md
  README.md
  action.yml
  config.js
  dist/LICENSE
  dist/index.js
  events/CommitCommentEvent.js
  events/CreateEvent.js
  events/ForkEvent.js
  events/GollumEvent.js
  events/IssueCommentEvent.js
  events/IssuesEvent.js
  events/MemberEvent.js
  events/PullRequestEvent.js
  events/PullRequestReviewCommentEvent.js
  events/PullRequestReviewEvent.js
  events/ReleaseEvent.js
  events/WatchEvent.js
  functions/appendDate.js
  functions/commitFile.js
  functions/filterContent.js
  functions/makeCustomUrl.js
  functions/parseYaml.js
  index.js
  package-lock.json
  package.json
  sample.yml
  serializers.js
Labels: Priority: medium, Status: Ready, Type: breaking, Type: enhancement, Updates: documentation, major

#59 Use src folder
  action.yml
  dist/index.js
  package-lock.json
  package.json
  src/config.js
  src/events/CommitCommentEvent.js
  src/events/CreateEvent.js
  src/events/ForkEvent.js
  src/events/GollumEvent.js
  src/events/IssueCommentEvent.js
  src/events/IssuesEvent.js
  src/events/MemberEvent.js
  src/events/PullRequestEvent.js
  src/events/PullRequestReviewCommentEvent.js
  src/events/PullRequestReviewEvent.js
  src/events/ReleaseEvent.js
  src/events/WatchEvent.js
  src/functions/appendDate.js
  src/functions/commitFile.js
  src/functions/execute.js
  src/functions/filterContent.js
  src/functions/makeCustomUrl.js
  src/functions/parseYaml.js
  src/functions/toUrlFormat.js
  src/index.js
  src/serializers.js
Labels: Priority: low, Status: In progress, Type: enhancement

#62 Add supported versions
  .github/CODEOWNERS
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  SUPPORTED_VERSIONS.md
Labels: Priority: high, Status: Ready, Type: enhancement, Updates: documentation

#63 Add custom committer
  dist/index.js
  docs/Configuration.md
  sample.yml
  src/config.js
  src/functions/commitFile.js
Labels: Priority: low, Status: Ready, Type: enhancement, minor

#64 Implement Wiki Update action
  .github/workflows/update_wiki.yml
  CHANGELOG.md
  docs/Examples.md
  docs/Home.md
  docs/README.md
Labels: No changelog, Status: Ready, Updates: documentation

#66 Improve images, badges and links in readme
  README.md
Labels: No changelog, Status: Ready, Updates: documentation

#67 Collect data from workflows
  CHANGELOG.md
  README.md
  dist/LICENSE
  dist/index.js
  package-lock.json
  package.json
  src/config.js
  src/functions/apiRequest.js
  src/functions/commitFile.js
  src/functions/execute.js
  src/functions/makeCustomUrl.js
  src/functions/toUrlFormat.js
Labels: Priority: medium, Status: In progress, Updates: documentation, minor

#68 Shift to glitch
  dist/index.js
  src/functions/apiRequest.js
Labels: Priority: high, Status: In progress, minor
