Repository Readme-Workflows/recent-activity, pull requests merged in 2021-07, with the labels that each got.

#75 Update README.md
  .tokeignore
  README.md
  SECURITY.md
  SUPPORTED_VERSIONS.md
Labels: Status: Ready, Updates: documentation

#77 Add whitelist feature
  .github/workflows/install.yml
  .github/workflows/run-build.yml
  dist/index.js
  src/config.js
  src/eventList.js
Labels: Priority: low, Status: Ready, Type: enhancement, minor

#78 Prepare Changelog
  CHANGELOG.md
Labels: No changelog, Status: Ready, Updates: documentation

#80 Create Setup Guide for wiki
  README.md
  docs/Home.md
  docs/Setup.md
  docs/_Sidebar.md
Labels: No changelog, Status: Ready, Updates: documentation

#81 Remove CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: Status: Ready
