Repository Readme-Workflows/recent-activity, pull requests merged in 2023-01, with the labels that each got.

#241 added feature to ignore repos
  dist/index.js
  sample.yml
  src/config.js
  src/functions/filterContent.js
Labels: Status: Ready

#242 Feature/Line Prefix
  .eslintrc.json
  .github/workflows/install.yml
  .github/workflows/run-build.yml
  action.yml
  dist/index.js
  package.json
  src/config.js
  src/index.js
Labels: Type: enhancement, minor, Status: In progress, Priority: low

#214 Update README.md
  README.md
Labels: Status: Ready

#247 added documentation for v2.4.1
  docs/Configuration.md
  docs/README.md
  sample.yml
Labels: Updates: documentation, Status: Ready, No changelog
